name: Run Pipeline Tests 2

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    name: run tests in docker image
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      COMPOSE_FILE: tests/docker-compose.yaml

    steps:
      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2

      - name: checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: log into github container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container

      - name: bake
        uses: docker/bake-action@v2.3.0
        with:
          workdir: tests
          load: true
          files: docker-compose.yaml
          set: |
            seechange_postgres.tags=ghcr.io/${{ github.repository_owner }}/seechange-postgres
            seechange_postgres.cache-from=type=gha,scope=cached-seechange-postgres
            seechange_postgres.cache-to=type=gha,scope=cached-seechange-postgres,mode=max
            setuptables.tags=ghcr.io/${{ github.repository_owner }}/runtests
            setuptables.cache-from=type=gha,scope=cached-seechange
            setuptables.cache-to=type=gha,scope=cached-seechange,mode=max
            runtests.tags=ghcr.io/${{ github.repository_owner }}/runtests
            runtests.cache-from=type=gha,scope=cached-seechange
            runtests.cache-to=type=gha,scope=cached-seechange,mode=max
            shell.tags=ghcr.io/${{ github.repository_owner }}/runtests
            shell.cache-from=type=gha,scope=cached-seechange
            shell.cache-to=type=gha,scope=cached-seechange,mode=max

      - name: run test
        run: |
          shopt -s nullglob
          TEST_SUBFOLDER=$(ls tests/pipeline/test_{p..z}*.py) docker compose run runtests
